### ISSUE TITLE
Action fails if trunk launcher is commited to repo

### ISSUE THREAD

**Issue by apgilfillan-cars** [trunk-io/trunk-action#16]
I've committed the trunk launcher as recommended in the documentation. It is located at the repo root.

But when the action runs I get the following failure
``` shell
Run trunk-io/trunk-action@v1.0.1
Run actions/cache@v2
  with:
    path: ~/.cache/trunk
    key: trunk-Linux-7d5ea510cff3bffd9ff8ce01953dbc50830181f[4](https://github.com/cars-data/di-spark_examples/runs/6234690543?check_suite_focus=true#step:3:4)282944e7f6294[5](https://github.com/cars-data/di-spark_examples/runs/6234690543?check_suite_focus=true#step:3:5)83d2fd3b97
Cache not found for input keys: trunk-Linux-7d5ea510cff3bffd9ff8ce01953dbc50830181f4282944e7f[6](https://github.com/cars-data/di-spark_examples/runs/6234690543?check_suite_focus=true#step:3:6)294583d2fd3b9[7](https://github.com/cars-data/di-spark_examples/runs/6234690543?check_suite_focus=true#step:3:7)
Run # Locate trunk
  # Locate trunk
  ${GITHUB_ACTION_PATH}/locate_trunk.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_TRUNK_PATH: 
Run # Determine check mode
  # Determine check mode
  ${GITHUB_ACTION_PATH}/determine_check_mode.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TRUNK_PATH: trunk
    INPUT_CHECK_MODE: 
Run # Run trunk check on pull request
Detected merge commit, using HEAD^1 (664990a640b3662b4c3[8](https://github.com/cars-data/di-spark_examples/runs/6234690543?check_suite_focus=true#step:3:8)554b2f55018efdfb870[9](https://github.com/cars-data/di-spark_examples/runs/6234690543?check_suite_focus=true#step:3:9)) as upstream
/home/runner/work/_actions/trunk-io/trunk-action/v1.0.1/pull_request.sh: line 29: trunk: command not found
Error: Process completed with exit code [12](https://github.com/cars-data/di-spark_examples/runs/6234690543?check_suite_focus=true#step:3:12)7.
Run # Cleanup temporary files
  # Cleanup temporary files
  ${GITHUB_ACTION_PATH}/cleanup.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TRUNK_PATH: trunk
    TRUNK_CHECK_MODE: pull_request
```

When I did not have the launcher committed to the repo the action ran fine. But afterwards I started encountering the error.  

Here is the workflow I am running
``` yaml
name: Pull Request
on: pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.0.1
```

Also love trunk. The design is super solid.
