### ISSUE TITLE
Trunk check failing in Github action even though it shows no issue

### ISSUE THREAD

**Issue by ryan-efendy** [trunk-io/trunk-action#6]
This is our PR workflow:

```
# pr.yml
name: PR workflow
on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - main
env:
    NODE_AUTH_TOKEN: ${{ secrets.GP_REPO_PACKAGE_R }}
jobs:
    pr:
        name: PR Checks
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cache Linters/Formatters
              uses: actions/cache@v2
              with:
                  path: ~/.cache/trunk
                  key: trunk-${{ runner.os }}

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Trunk Check
              uses: trunk-io/trunk-action@v0.4.0-beta
```

Trunk check shows no issue:
![image](https://user-images.githubusercontent.com/12979345/150555921-07be87a3-2a38-401a-9dab-ffa25031b704.png)

But in the Github action we're getting below:
![image](https://user-images.githubusercontent.com/12979345/150555726-e09793c2-67c0-42ae-a470-e5dd9f26a236.png)

Can you help us understand what's going on?
