### ISSUE TITLE
Trunk Check functionality

### ISSUE THREAD

**Issue by chris3ware** [trunk-io/trunk-action#7]
Hi, I just wondered about the behaviour of the action when it runs. Trunk Check runs with a number of other actions in my repository. It's running fine, spotting issues where they arise and outputting the results. However, where it outputs the results is a little confusing. It appears to attach to another workflow as shown below.

I have the following trunk check workflow file:

```yaml
name: Trunk Check
on: pull_request

jobs:
  main:
    name: Trunk Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Linters/Formatters
        uses: actions/cache@v2
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}
      - name: Trunk Check
        uses: trunk-io/trunk-action@v0.4.0-beta
```

And the workflow outputs can been seen from the "Check" tab in the pull request:

<img width="345" alt="Screenshot 2022-01-27 at 12 40 52" src="https://user-images.githubusercontent.com/36608309/151360867-8789d562-39d6-462e-9a5d-fc1b4f3224b9.png">

Clicking on "Trunk Check" takes me to Github Actions, where I can see the workflow logs.

"Trunk Check" Is also shown under my "semantic-release" check

Clicking on "Trunk Check" here, stays on the pull request checks tab and displays the trunk check output:

<img width="655" alt="Screenshot 2022-01-27 at 12 46 47" src="https://user-images.githubusercontent.com/36608309/151361713-149af732-77d1-4d48-b8f4-4af1d2ffe16f.png">

For clarify, here is my semanitc-release workflow file:

```yaml
name: semantic-pull-request
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

As you can see it doesn't mention running "Trunk Check" anywhere in this file, but for some reason the results of the Trunk Check workflow are added to this workflow. 

So, nothing is "broken" as such, everything works. I'm just a bit confused by this behaviour and if it is expected?

Cheers
Chris
